Crime.create(:id => 1, :crime => "HOMICIDIO")
Crime.create(:id => 2, :crime => "LESIONES")
Crime.create(:id => 3, :crime => "AYUDA O INDUCCION AL SUICIDIO")
Crime.create(:id => 4, :crime => "ABORTO")
Crime.create(:id => 5, :crime => "PROCREACION ASISTIDA")
Crime.create(:id => 6, :crime => "INSEMINACION ARTIFICIAL")
Crime.create(:id => 7, :crime => "MANIPULACION GENETICA")
Crime.create(:id => 8, :crime => "OMISION DE AUXILIO O DE CUIDADO")
Crime.create(:id => 9, :crime => "PELIGRO DE CONTAGIO")
Crime.create(:id => 10, :crime => "PRIVACION DE LA LIBERTAD PERSONAL")
Crime.create(:id => 11, :crime => "PRIVACION DE LA LIBERTAD CON FINES SEXUALES")
Crime.create(:id => 12, :crime => "SECUESTRO")
Crime.create(:id => 13, :crime => "DESAPARICION FORZADA DE PERSONAS")
Crime.create(:id => 14, :crime => "TRAFICO DE MENORES")
Crime.create(:id => 15, :crime => "RETENCION Y SUSTRACCION DE PERSONAS MENORES DE EDAD")
Crime.create(:id => 17, :crime => "ABUSO SEXUAL")
Crime.create(:id => 18, :crime => "HOSTIGAMIENTO SEXUAL")
Crime.create(:id => 19, :crime => "ESTUPRO")
Crime.create(:id => 20, :crime => "INCESTO")
Crime.create(:id => 21, :crime => "DELITO CONTRA LA FORMACION DE MENORES DE EDAD")
Crime.create(:id => 22, :crime => "DELITOS CONTRA LA FORMACION DE PERSONAS QUE NO TIENEN CAPACIDAD PARA COMPRENDER EL SIGNIFICADO DEL HECHO")
Crime.create(:id => 23, :crime => "PORNOGRAFIA CON PERSONAS MENORES DE EDAD")
Crime.create(:id => 24, :crime => "PORNOGRAFIA CON PERSONAS QUE NO TIENEN CAPACIDAD PARA COMPRENDER EL SIGNIFICADO DEL HECHO")
Crime.create(:id => 25, :crime => "INCUMPLIMIENTO DE LA OBLIGACION ALIMENTARIA")
Crime.create(:id => 27, :crime => "ALTERACION DEL ESTADO CIVIL DE LAS PERSONAS")
Crime.create(:id => 28, :crime => "BIGAMIA")
Crime.create(:id => 29, :crime => "DELITO CONTRA LA DISCRIMINACION")
Crime.create(:id => 30, :crime => "TRATA DE PERSONAS")
Crime.create(:id => 31, :crime => "LENOCINIO")
Crime.create(:id => 32, :crime => "DELITO DE INHUMACION DE CADAVERES")
Crime.create(:id => 33, :crime => "DELITO DE EXHUMACION DE CADAVERES O RESTOS HUMANOS")
Crime.create(:id => 34, :crime => "AMENAZAS")
Crime.create(:id => 35, :crime => "ALLANAMIENTO DE VIVIENDA, DESPACHO, OFICINA O ESTABLECIMIENTO MERCANTIL")
Crime.create(:id => 36, :crime => "REVELACION DE SECRETOS")
Crime.create(:id => 37, :crime => "ROBO")
Crime.create(:id => 38, :crime => "ROBO DE GANADO")
Crime.create(:id => 39, :crime => "ROBO DE VEHICULO")
Crime.create(:id => 40, :crime => "ABUSO DE CONFIANZA")
Crime.create(:id => 41, :crime => "FRAUDE")
Crime.create(:id => 42, :crime => "ADMINISTRACION FRAUDULENTA")
Crime.create(:id => 43, :crime => "INSOLVENCIA FRAUDULENTA EN PERJUICIO DE ACREEDORES")
Crime.create(:id => 44, :crime => "USURA")
Crime.create(:id => 45, :crime => "EXTORSION")
Crime.create(:id => 46, :crime => "DESPOJO")
Crime.create(:id => 47, :crime => "DAÑOS")
Crime.create(:id => 48, :crime => "ENCUBRIMIENTO POR RECEPTACION")
Crime.create(:id => 49, :crime => "DELITO DE OPERACIONES CON RECURSOS DE PROCEDENCIA ILICITA")
Crime.create(:id => 50, :crime => "ASOCIACION DELICTUOSA")
Crime.create(:id => 51, :crime => "DELINCUENCIA ORGANIZADA")
Crime.create(:id => 52, :crime => "ASALTOS")
Crime.create(:id => 53, :crime => "EJERCICIO ILEGAL ABANDONO DEL SERVICIO PUBLICO")
Crime.create(:id => 54, :crime => "ABANDONO DEL SERVICIO PUBLICO")
Crime.create(:id => 55, :crime => "ABUSO DE AUTORIDAD")
Crime.create(:id => 56, :crime => "USO ILEGAL DE LA FUERZA PUBLICA")
Crime.create(:id => 57, :crime => "COALISION DE SERVIDORES PUBLICOS")
Crime.create(:id => 58, :crime => "USO ILEGAL DE ATRIBUCIONES Y FACULTADES")
Crime.create(:id => 59, :crime => "INTIMIDACION")
Crime.create(:id => 60, :crime => "NEGACION DEL SERVICIO PUBLICO")
Crime.create(:id => 61, :crime => "TRAFICO DE INFLUENCIAS")
Crime.create(:id => 62, :crime => "COHECHO")
Crime.create(:id => 63, :crime => "PECULADO")
Crime.create(:id => 64, :crime => "CONCUSION")
Crime.create(:id => 65, :crime => "ENRIQUECIMIENTO ILICITO COMETIDO POR SERVIDOR PUBLICO")
Crime.create(:id => 66, :crime => "PROMOCION DE CONDUCTAS ILICITAS")
Crime.create(:id => 67, :crime => "ENRIQUECIMIENTO ILICITO COMETIDO POR PARTICULAR")
Crime.create(:id => 68, :crime => "DESOBEDIENCIA DE UN MANDATO DE AUTORIDAD")
Crime.create(:id => 69, :crime => "RESISTENCIA DE PARTICULARES")
Crime.create(:id => 70, :crime => "OPOSICION A QUE SE EJECUTE ALGUNA OBRA O TRABAJO PUBLICO")
Crime.create(:id => 71, :crime => "QUEBRANTAMIENTO DE SELLOS")
Crime.create(:id => 72, :crime => "ULTRAJES A LA AUTORIDAD")
Crime.create(:id => 73, :crime => "EJERCICIO ILEGAL DEL PROPIO DERECHO")
Crime.create(:id => 74, :crime => "USURPACION DE FUNCIONES PUBLICAS")
Crime.create(:id => 75, :crime => "DENEGACION O RETARDO DE JUSTICIA")
Crime.create(:id => 76, :crime => "PREVARICACION")
Crime.create(:id => 77, :crime => "DELITOS EN EL AMBITO DE LA PROCURACION DE JUSTICIA")
Crime.create(:id => 78, :crime => "TORTURA")
Crime.create(:id => 79, :crime => "DELITOS EN EL AMBITO DE LA ADMINISTRACION DE JUSTICIA")
Crime.create(:id => 80, :crime => "OMISION DE INFORMES MEDICO-FORENSES")
Crime.create(:id => 81, :crime => "DELITOS COMETIDOS EN EL AMBITO DE LA EJECUCION PENAL")
Crime.create(:id => 82, :crime => "EVASION DE PRESOS")
Crime.create(:id => 83, :crime => "FRAUDE PROCESAL")
Crime.create(:id => 84, :crime => "FALSEDAD ANTE AUTORIDAD")
Crime.create(:id => 85, :crime => "VARIACION DEL NOMBRE O DOMICILIO")
Crime.create(:id => 86, :crime => "SIMULACION DE PRUEBAS")
Crime.create(:id => 87, :crime => "DELITOS DE ABOGADOS, PATRONOS Y LITIGANTES")
Crime.create(:id => 88, :crime => "ENCUBRIMIENTO POR FAVORECIMIENTO")
Crime.create(:id => 89, :crime => "RESPONSABILIDAD PROFESIONAL Y TECNICA")
Crime.create(:id => 90, :crime => "USURPACION DE PROFESION")
Crime.create(:id => 91, :crime => "PRACTICA INDEBIDA DEL SERVICIO MEDICO")
Crime.create(:id => 92, :crime => "RESPONSABILIDAD DE PERSONAL DE CENTROS DE SALUD Y ESTABLECIMIENTOS FUNERARIOS")
Crime.create(:id => 93, :crime => "SUMINISTRO DE MEDICINAS NOCIVAS O INAPROPIADAS")
Crime.create(:id => 94, :crime => "ATAQUES A LAS VIAS DE COMUNICACION")
Crime.create(:id => 95, :crime => "ATAQUES A LOS MEDIOS DE TRANSPORTE")
Crime.create(:id => 96, :crime => "VIOLACION DE CORRESPONDENCIA")
Crime.create(:id => 97, :crime => "VIOLACION DE LA COMUNICACIÓN PRIVADA")
Crime.create(:id => 98, :crime => "FALSIFICACION DE SELLOS, MARCAS, LLAVES Y OTROS")
Crime.create(:id => 99, :crime => "ELABORACION O ALTERACION DE USO INDEBIDO DE PLACAS, ENGOMADOS Y DOCUMENTOS DE IDENTIFICACION DE VEHICULOS")
Crime.create(:id => 100, :crime => "FALSIFICACION O ALTERACION Y USO INDEBIDO DE DOCUMENTOS")
Crime.create(:id => 101, :crime => "COMETIDOS POR SERVIDORES PUBLICOS")
Crime.create(:id => 102, :crime => "COMETIDOS POR PARTICULARES")
Crime.create(:id => 103, :crime => "POR FUNCIONARIOS ELECTORALES")
Crime.create(:id => 104, :crime => "POR FUNCIONARIO PARTIDISTA")
Crime.create(:id => 105, :crime => "REBELION")
Crime.create(:id => 106, :crime => "ATAQUES A LA PAZ PUBLICA")
Crime.create(:id => 107, :crime => "SABOTAJE")
Crime.create(:id => 108, :crime => "MOTIN")
Crime.create(:id => 109, :crime => "SEDICION")
Crime.create(:id => 110, :crime => "DELITOS ELECTORALES")
Crime.create(:id => 112, :crime => "ROBO DE AUTOPARTES O ACCESORIOS")
Crime.create(:id => 135, :crime => "USO Y ACCESO ILICITO A LOS SISTEMAS Y EQUIPOS INFORMATICOS Y DE COMUNICACION")
Crime.create(:id => 111, :crime => "SUICIDIO (HECHO NO DELICTIVO)")
Crime.create(:id => 114, :crime => "MUERTE ACCIDENTAL (HECHO NO DELICTIVO)")
Crime.create(:id => 115, :crime => "MUERTE NATURAL (HECHO NO DELICTIVO)")
Crime.create(:id => 16, :crime => "VIOLACION")
Crime.create(:id => 26, :crime => "VIOLENCIA FAMILIAR")
Crime.create(:id => 133, :crime => "VEHICULO ROBADO - CONDUCTAS ESTABLECIDAS EN EL ART. 212 BIS.")
Crime.create(:id => 120, :crime => "PORTACION DE ARMA DE FUEGO")
Crime.create(:id => 121, :crime => "PORTACION DE CARTUCHOS")
Crime.create(:id => 122, :crime => "INTRODUCCION AL PAIS DE ARMAS DE FUEGO")
Crime.create(:id => 123, :crime => "INTRODUCCION AL PAIS DE CARTUCHOS")
Crime.create(:id => 124, :crime => "ACOPIO DE ARMAS")
Crime.create(:id => 125, :crime => "FABRICACION DE ARMAS")
Crime.create(:id => 126, :crime => "COMPRA DE EXPLOSIVOS")
Crime.create(:id => 127, :crime => "TRANSPORTE DE EXPLOSIVOS")
Crime.create(:id => 128, :crime => "ALMACENAMIENTO DE EXPLOSIVOS")
Crime.create(:id => 129, :crime => "FABRICACION DE EXPLOSIVOS")
Crime.create(:id => 130, :crime => "CONTRA LA SALUD")
Crime.create(:id => 131, :crime => "DELITOS AMBIENTALES")
Crime.create(:id => 132, :crime => "USO DE MONEDA FALSA")
Crime.create(:id => 113, :crime => "TRATA DE PERSONAS DE INDOLE SEXUAL")
Crime.create(:id => 116, :crime => "ROBO AGROPECUARIO")
Crime.create(:id => 117, :crime => "FRAUDE AGROPECUARIO")
Crime.create(:id => 134, :crime => "DELITOS CONTRA EL DESARROLLO ZOOSANITARIO")
