Place.create(:id => 1, :place => "No especificado")
Place.create(:id => 2, :place => "Abarrotes")
Place.create(:id => 3, :place => "Aeropuerto")
Place.create(:id => 4, :place => "Agencia de vehículos")
Place.create(:id => 5, :place => "Agencia de viajes")
Place.create(:id => 6, :place => "Alarmas")
Place.create(:id => 7, :place => "Banco - cajero automático")
Place.create(:id => 8, :place => "Banco - oficina mayor")
Place.create(:id => 9, :place => "Banco - sucursal o mini banco")
Place.create(:id => 10, :place => "Bar o cantina")
Place.create(:id => 11, :place => "Basurero")
Place.create(:id => 12, :place => "Bodega")
Place.create(:id => 13, :place => "Brecha / terracería")
Place.create(:id => 14, :place => "Cafetería")
Place.create(:id => 15, :place => "Campo menonita")
Place.create(:id => 17, :place => "Carretera")
Place.create(:id => 18, :place => "Casa de cambio")
Place.create(:id => 19, :place => "Casa habitación")
Place.create(:id => 20, :place => "Celulares")
Place.create(:id => 21, :place => "Central camionera")
Place.create(:id => 22, :place => "Centro cultural")
Place.create(:id => 23, :place => "Centro de copiado")
Place.create(:id => 24, :place => "Centro deportivo")
Place.create(:id => 25, :place => "Centro penitenciario (CERESO-cárcel)")
Place.create(:id => 27, :place => "Cerrajería")
Place.create(:id => 28, :place => "Computadoras / equipo de computo")
Place.create(:id => 29, :place => "Comunicaciones")
Place.create(:id => 30, :place => "Comunidad indígena")
Place.create(:id => 31, :place => "Comunidad mormona")
Place.create(:id => 32, :place => "Constructora")
Place.create(:id => 33, :place => "Consultorio medico")
Place.create(:id => 34, :place => "Desponchado")
Place.create(:id => 35, :place => "Discoteca")
Place.create(:id => 36, :place => "Ejido")
Place.create(:id => 37, :place => "Embotelladora")
Place.create(:id => 38, :place => "Escuela particular")
Place.create(:id => 39, :place => "Escuela pública")
Place.create(:id => 40, :place => "Estación de ferrocarril")
Place.create(:id => 41, :place => "Estacionamiento público")
Place.create(:id => 42, :place => "Farmacia")
Place.create(:id => 43, :place => "Ferretería")
Place.create(:id => 44, :place => "Florería / regalos")
Place.create(:id => 45, :place => "Gasera")
Place.create(:id => 46, :place => "Gasolinera")
Place.create(:id => 47, :place => "Guardería")
Place.create(:id => 48, :place => "Herrería, taller de")
Place.create(:id => 49, :place => "Hospital")
Place.create(:id => 50, :place => "Hotel")
Place.create(:id => 51, :place => "Iglesia")
Place.create(:id => 52, :place => "Imprenta")
Place.create(:id => 53, :place => "Inmobiliaria")
Place.create(:id => 54, :place => "Joyería / relojería")
Place.create(:id => 55, :place => "Laboratorio")
Place.create(:id => 56, :place => "Lavandería")
Place.create(:id => 57, :place => "Llantera")
Place.create(:id => 58, :place => "Lote venta vehículos")
Place.create(:id => 59, :place => "Maderera")
Place.create(:id => 60, :place => "Maquiladora / fábrica")
Place.create(:id => 61, :place => "Mercado público")
Place.create(:id => 62, :place => "Mini súper")
Place.create(:id => 63, :place => "Mueblería")
Place.create(:id => 64, :place => "Negocio (otros)")
Place.create(:id => 65, :place => "Notaría")
Place.create(:id => 66, :place => "Oficina privada")
Place.create(:id => 67, :place => "Oficina pública")
Place.create(:id => 68, :place => "Óptica")
Place.create(:id => 69, :place => "Panteón o cementerio")
Place.create(:id => 70, :place => "Papelería")
Place.create(:id => 71, :place => "Parque, plaza pública")
Place.create(:id => 72, :place => "Peluquería / estilistas")
Place.create(:id => 73, :place => "Pinturas")
Place.create(:id => 74, :place => "Presa, lago o laguna")
Place.create(:id => 75, :place => "Puesto de comida")
Place.create(:id => 76, :place => "Ranchería / localidad rural")
Place.create(:id => 77, :place => "Rancho / huerta privada")
Place.create(:id => 78, :place => "Refaccionaria")
Place.create(:id => 79, :place => "Restaurante (grande)")
Place.create(:id => 80, :place => "Restaurante autoservicio")
Place.create(:id => 81, :place => "Ropa")
Place.create(:id => 82, :place => "Salón de eventos")
Place.create(:id => 83, :place => "Supermercado")
Place.create(:id => 84, :place => "Taller")
Place.create(:id => 85, :place => "Terreno baldío / tapias")
Place.create(:id => 86, :place => "Tortillería")
Place.create(:id => 87, :place => "Transportes")
Place.create(:id => 88, :place => "Vecindad")
Place.create(:id => 89, :place => "Vía pública (calles, avenidas, etc.)")
Place.create(:id => 90, :place => "Vías de ferrocarril")
Place.create(:id => 91, :place => "Videoclub / renta de videos")
Place.create(:id => 92, :place => "Vinos y licores")
Place.create(:id => 93, :place => "Yonke / partes usadas / chatarra")
Place.create(:id => 94, :place => "Zapatería")
Place.create(:id => 95, :place => "Zona rural (otros)")
Place.create(:id => 96, :place => "Zona urbana (lugar público, otros)")
Place.create(:id => 97, :place => "Rancho o Huerta Privados")
Place.create(:id => 98, :place => "Refaccionarias")
Place.create(:id => 99, :place => "Restaurante (Grande)")
Place.create(:id => 100, :place => "Restaurante Autoservicio")
Place.create(:id => 101, :place => "Ropa")
Place.create(:id => 102, :place => "Funeraria")
