# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: oracle_enhanced
  database: xe
  host: 192.168.1.106
  username: mexico2
  password: mexico2
  port: 1521

